# Generated by Django 4.2.7 on 2026-03-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV / Crossover'), ('pickup', 'Pickup Truck'), ('van', 'Van / Minivan'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('wagon', 'Station Wagon'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('other', 'Other')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('for_parts', 'For Parts')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive (FWD)'), ('rwd', 'Rear-Wheel Drive (RWD)'), ('awd', 'All-Wheel Drive (AWD)'), ('4wd', '4-Wheel Drive (4WD)')], max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='engine_size',
            field=models.CharField(blank=True, help_text='e.g. 1.5L, 2.0L', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_abs',
            field=models.BooleanField(default=False, verbose_name='ABS Brakes'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_airbags',
            field=models.BooleanField(default=False, verbose_name='Airbags'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_alarm',
            field=models.BooleanField(default=False, verbose_name='Car Alarm / Immobilizer'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_backup_camera',
            field=models.BooleanField(default=False, verbose_name='Backup Camera'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth / Audio'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_gps',
            field=models.BooleanField(default=False, verbose_name='GPS Navigation'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_insurance',
            field=models.BooleanField(default=False, verbose_name='With Insurance'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_leather_seats',
            field=models.BooleanField(default=False, verbose_name='Leather Seats'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_power_steering',
            field=models.BooleanField(default=False, verbose_name='Power Steering'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_power_windows',
            field=models.BooleanField(default=False, verbose_name='Power Windows'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_spare_tire',
            field=models.BooleanField(default=False, verbose_name='Spare Tire'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_sunroof',
            field=models.BooleanField(default=False, verbose_name='Sunroof / Moonroof'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='has_tinted',
            field=models.BooleanField(default=False, verbose_name='Tinted Windows'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='horsepower',
            field=models.IntegerField(blank=True, help_text='in hp', null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Registered (OR/CR Complete)'),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='num_doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4', max_length=5),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='num_seats',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='5', max_length=5),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Optional', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Mitsubishi', 'Mitsubishi'), ('Suzuki', 'Suzuki'), ('Ford', 'Ford'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Isuzu', 'Isuzu'), ('Chevrolet', 'Chevrolet'), ('Mazda', 'Mazda'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Volkswagen', 'Volkswagen'), ('Subaru', 'Subaru'), ('Lexus', 'Lexus'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], max_length=20),
        ),
    ]
